import { createElement } from 'react';
import {
  AlignJustify,
  CheckCircle2,
  CheckSquare,
  CircleDot,
  FileText,
  Grid3X3,
  HelpCircle,
  ImageIcon,
  Layers,
  List as ListIcon,
  ListOrdered,
  Minus,
  Split,
  Table as TableIcon,
  Type,
} from 'lucide-react';

export const QUESTION_TYPE_DEFINITIONS = [
  {
    id: 'multiple',
    label: 'Понудени одговори',
    icon: CheckSquare,
    cat: 'базични',
    subjects: ['all'],
    priority: 10,
  },
  {
    id: 'true-false',
    label: 'Точно/Неточно',
    icon: HelpCircle,
    cat: 'базични',
    subjects: ['all'],
    priority: 9,
  },
  {
    id: 'fill-blanks',
    label: 'Пополни празнини',
    icon: Minus,
    cat: 'текстуални',
    subjects: ['languages', 'history'],
    priority: 8,
  },
  {
    id: 'selection',
    label: 'Селекција (Инлајн)',
    icon: CircleDot,
    cat: 'напредни',
    subjects: ['languages'],
    priority: 7,
  },
  {
    id: 'multi-match',
    label: 'Мулти-поврзување',
    icon: Grid3X3,
    cat: 'логички',
    subjects: ['stem', 'all'],
    priority: 6,
  },
  {
    id: 'short-answer',
    label: 'Краток одговор',
    icon: Type,
    cat: 'текстуални',
    subjects: ['all'],
    priority: 10,
  },
  {
    id: 'essay',
    label: 'Есеј / Долг одговор',
    icon: FileText,
    cat: 'текстуални',
    subjects: ['languages', 'history'],
    priority: 5,
  },
  {
    id: 'matching',
    label: 'Поврзување',
    icon: Split,
    cat: 'логички',
    subjects: ['all'],
    priority: 8,
  },
  {
    id: 'ordering',
    label: 'Подредување',
    icon: ListOrdered,
    cat: 'логички',
    subjects: ['history', 'stem', 'geometry'],
    priority: 7,
  },
  {
    id: 'list',
    label: 'Листа (набројување)',
    icon: ListIcon,
    cat: 'листа',
    subjects: ['all'],
    priority: 6,
  },
  {
    id: 'table',
    label: 'Табела',
    icon: TableIcon,
    cat: 'напредни',
    subjects: ['stem'],
    priority: 9,
  },
  {
    id: 'multi-part',
    label: 'Мулти-дел (а, б, в)',
    icon: Layers,
    cat: 'напредни',
    subjects: ['stem'],
    priority: 8,
  },
  {
    id: 'section',
    label: 'Наслов на Секција',
    icon: AlignJustify,
    cat: 'напредни',
    subjects: ['all'],
    priority: 5,
  },
  {
    id: 'diagram',
    label: 'Дијаграм / Цртеж',
    icon: ImageIcon,
    cat: 'напредни',
    subjects: ['stem', 'geography', 'geometry'],
    priority: 7,
  },
  {
    id: 'statements',
    label: 'Изјави (Т/Н листа)',
    icon: CheckCircle2,
    cat: 'базични',
    subjects: ['all'],
    priority: 8,
  },
  {
    id: 'checklist',
    label: 'Повеќекратен избор',
    icon: CheckSquare,
    cat: 'базични',
    subjects: ['all'],
    priority: 7,
  },
];

export function buildQuestionTypes() {
  return QUESTION_TYPE_DEFINITIONS.map((item) => ({
    ...item,
    icon: createElement(item.icon, { size: 16 }),
  }));
}
